[tool.cibuildwheel]
skip = ["*_i686", "*_ppc64le", "*_s390x", "*_universal2"]
# We're only testing with essential test dependencies, not optional ones.
# Some of those require binary wheels (often missing for some platforms),
# or they slow down the test suite runs too much or simply aren't necessary.
test-requires = [
    "pytest",
    "pytest-xdist",
    "threadpoolctl",
    "pooch",
    "hypothesis",
]
before-build = "bash {project}/tools/wheels/cibw_before_build.sh {project}"
test-command = "bash {project}/tools/wheels/cibw_test_command.sh {project}"

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
musllinux-x86_64-image = "musllinux_1_2"
musllinux-aarch64-image = "musllinux_1_2"

[tool.cibuildwheel.linux.environment]
# RUNNER_OS is a GitHub Actions specific env var; define it here so it's
# defined when running cibuildwheel locally
RUNNER_OS="Linux"
# /project will be the $PWD equivalent inside the Docker container used to build the wheel
PKG_CONFIG_PATH="/project/.openblas"

[tool.cibuildwheel.macos.environment]
PKG_CONFIG_PATH = "{project}"

[tool.cibuildwheel.windows]
repair-wheel-command = "bash ./tools/wheels/repair_windows.sh {wheel} {dest_dir}"
